accounts/urls.py
from django.urls import path
from .views import sign_up, verify_login_phone


urlpatterns = [



    path('signup/', sign_up, name='signup'),

    path('verify/', verify_login_phone, name='verify'),
]

cart/urls.py
from django.urls import path

from .views import detail_cart, add_to_cart, remove_cart, clear_cart

app_name = 'cart'

urlpatterns = [
    path('', detail_cart, name='cart'),
    path('add/<int:product_id>/', add_to_cart, name='add_cart'),
    path('remove/<int:product_id>/', remove_cart, name='remove_cart'),
    path('clear/', clear_cart, name='clear_cart'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('rosetta/', include('rosetta.urls')),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('', include('books.urls')),
                  path('detail/', include('pages.urls')),
                  path('news/', include('posts.urls')),
                  path('cart/', include('cart.urls')),

              ] + static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                     document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    phone = models.IntegerField(null=True)

accounts/forms.py
import platform

from django import forms
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm


class RegisterForm(forms.Form):
    user_name = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput())
    email = forms.EmailField()


class LoginForm(forms.Form):
    user_name = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput())


class UserCreationForm(BaseUserCreationForm):
    phone = forms.IntegerField()

    class Meta:
        model = CustomUser
        fields = ('username', 'phone', 'password1', 'password2')



class LoginPhoneForm(forms.Form):
    phone = forms.IntegerField()



class CodePhoneForm(forms.Form):
    code = forms.IntegerField()

accounts/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.views import generic
from django.urls import reverse_lazy
from .forms import RegisterForm, LoginForm, LoginPhoneForm, CodePhoneForm, UserCreationForm
from django.contrib.auth.models import User
import ghasedakpack
from django.contrib.auth import authenticate, login, logout
from random import randint
from django.views import generic
from django.contrib import messages
from django.urls import reverse_lazy
from .models import CustomUser


def sign_up(request):
    if request.method == 'POST':
        form1 = UserCreationForm(request.POST)
        if form1.is_valid():


            global random_code, phone, new_form,data
            data = form1.cleaned_data
            phone = f"0{data['phone']}"
            random_code = randint(1000, 9999)
            sms = ghasedakpack.Ghasedak("96717c350e773ed6410cfe43799eb5951d1b0cfb6fc750d5b2fdff5d73d03081")
            sms.send({'message': random_code, 'receptor': phone, 'linenumber': "10008566"})
            new_form = form1.save(commit=False)
            return redirect('verify')
    else:
        form1 = UserCreationForm()

    context = {
        'form': form1,
    }
    return render(request, 'accounts/signup.html', context)


def verify_login_phone(request):
    if request.method == 'POST':
        form = CodePhoneForm(request.POST)
        if form.is_valid():
            if random_code == form.cleaned_data['code']:

                new_form.save()
                user = authenticate(request, username=data['username'], password=data['password1'])
                if user is not None:
                    login(request, user)

                return redirect('home')
            else:
                messages.error(request, 'کد وارد شده اشتباه است')
    else:
        form = CodePhoneForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/verify-login-phone.html', context)














#
# def sign_up(request):
#     if request.method == 'POST':
#         form = RegisterForm(request.POST)
#         if form.is_valid():
#             data = form.cleaned_data
#             User.objects.create_user(username=data['user_name'], password=data['password'], email=data['email'])
#
#         return redirect('home')
#     else:
#         form = RegisterForm()
#     context = {'form': form}
#     return render(request, 'accounts/signup.html', context)
#
#
# def login_view(request):
#     if request.method == 'POST':
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             data = form.cleaned_data
#             try:
#                 user = authenticate(request, username=User.objects.get(email=data['user_name']),
#                                     password=data['password'])
#             except:
#                 user = authenticate(request, username=data['user_name'], password=data['password'])
#             if user is not None:
#                 login(request, user)
#                 return redirect('home')
#     else:
#         form = LoginForm()
#     return render(request, 'accounts/login.html', {'form': form})
#
#
# def logout_view(request):
#     logout(request)
#     return redirect('home')
#
#

#
#
# def login_phone(request):
#     if request.method == 'POST':
#         form = LoginPhoneForm(request.POST)
#         if form.is_valid():
#             global random_code, phone
#             data = form.cleaned_data
#             phone = f"0{data['phone']}"
#             random_code = randint(1000, 9999)
#             sms = ghasedakpack.Ghasedak("96717c350e773ed6410cfe43799eb5951d1b0cfb6fc750d5b2fdff5d73d03081")
#             sms.send({'message': random_code, 'receptor': phone, 'linenumber': "10008566"})
#
#             return redirect('verify')
#     else:
#         form = LoginPhoneForm()
#
#     context = {
#         'form': form,
#     }
#     return render(request, 'accounts/login-phone.html', context)
#
#
#

accounts/templates/accounts/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=chrome">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign up</title>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
</head>
<body>
<!-- O P E N : REGISTER CONTAINER -->
<div id="register">
    <!-- O P E N : LEFT SECTION -->
    <div class="left-sec">
        <h2>Welcome Back !</h2>
        <p>This is some test text to create an register form</p>
        <a href="{% url 'signup' %}" class="signin-btn">SIGN IN</a>
        <a href="{% url 'home' %}" class="signin-btn"> HOME</a>
    </div>
    <!-- C L O S E : LEFT SECTION -->

    <!-- O P E N : RIGHT SECTION -->
    <div class="right-sec">
        <h2>Create Account</h2>
        <p> use your user name to login</p>

        <form action="{% url 'signup' %}" class="signin-form" method="POST">
            {% csrf_token %}

            <img src="{% static 'images/user.png' %}" alt="user">
            <label for="id_username"></label>
            <input type="text" placeholder="Name" class="form-input" name="username" autofocus="" autocapitalize="none"
                   autocomplete="username" maxlength="150" required="" id="id_username">
            <br>
            <img src="{% static 'images/phone.png' %}" alt="pw">
            <label for="id_phone"></label>
            <input class="form-input" placeholder="phone number" type="number" name="phone" required="" id="id_phone">

            <br>

            <img src="{% static 'images/password.png' %}" alt="pw">
            <label for="id_password1"></label>
            <input type="password" placeholder="Password" class="form-input"
                   name="password1" autocomplete="new-password" required="" id="id_password1">
            <br>
            <img src="{% static 'images/password.png' %}" alt="pw">
            <label for="id_password2"></label>
            <input type="password" placeholder="confirm Password" class="form-input"
                   name="password2" autocomplete="new-password" required="" id="id_password2">
            <br>

            <input type="submit" value="SIGN UP " class="signup-btn">

        </form>
        <!-- C L O S E : RIGHT SECTION -->

    </div>
</div>
<!-- C L O S E : REGISTER CONTAINER -->
</body>
</html>

accounts/templates/accounts/verify-login-phone.html
{% load static %}
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=chrome">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>verify code</title>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
</head>
<body>
<!-- O P E N : REGISTER CONTAINER -->
<div id="register">
    <!-- O P E N : LEFT SECTION -->
    <div class="left-sec">
        <h2>Welcome Back !</h2>
        <p>This is some test text to create an register form</p>
        <a href="{% url 'signup' %}" class="signin-btn">SIGN IN</a>
        <a href="{% url 'home' %}" class="signin-btn"> HOME</a>
    </div>
    <!-- C L O S E : LEFT SECTION -->

    <!-- O P E N : RIGHT SECTION -->
    <div class="right-sec">
        <h2>Confirm code</h2>
        <p> please Enter the code sent</p>

        <form action="{% url 'verify' %}" class="signin-form" method="POST">
            {% csrf_token %}

                <img src="{% static 'images/password.png' %}" alt="user">
                <label for="id_code"></label>

                <input type="number" name="code" required="" id="id_code" placeholder="Name" class="form-input">
                <br>

                <input type="submit" value="Send " class="signup-btn">

        </form>
        <!-- C L O S E : RIGHT SECTION -->

    </div>
</div>
<!-- C L O S E : REGISTER CONTAINER -->
</body>
</html>